/*
# Expand product catalog to comprehensive grocery list

1. Changes
- Upserts 962 grocery products spanning staples, grains, pulses, oils, spices, sauces, biscuits, snacks, cereals, noodles, tea, coffee, beverages, dairy, dry fruits, bakery, vegetables, leafy greens, fruits, and regional Indian produce.
- Each product has a name, category, unit, and four deterministic source prices (BigBasket, Blinkit, Zepto, Swiggy Instamart).
- Prices are generated from category base prices and a stable hash of the product name, so the same product always returns the same prices.
2. Idempotency
- Uses ON CONFLICT (name, unit) DO UPDATE so re-running updates existing products without creating duplicates.
3. Security
- No policy changes. The products table remains publicly readable (anon + authenticated).
*/

WITH seed_data(name, category, unit, base_price) AS (
  VALUES
  ('Basmati Rice', 'Staples & Grains', 'kg', 120::numeric),
  ('Sella Basmati Rice', 'Staples & Grains', 'kg', 120::numeric),
  ('Brown Basmati Rice', 'Staples & Grains', 'kg', 120::numeric),
  ('Jasmine Rice', 'Staples & Grains', 'kg', 120::numeric),
  ('Gobindobhog Rice', 'Staples & Grains', 'kg', 120::numeric),
  ('White Rice', 'Staples & Grains', 'kg', 55::numeric),
  ('Kolam Rice', 'Staples & Grains', 'kg', 55::numeric),
  ('Sona Masoori Rice', 'Staples & Grains', 'kg', 55::numeric),
  ('Ponni Rice', 'Staples & Grains', 'kg', 55::numeric),
  ('Idli Rice', 'Staples & Grains', 'kg', 55::numeric),
  ('Brown Rice', 'Staples & Grains', 'kg', 55::numeric),
  ('Poha', 'Staples & Grains', 'kg', 45::numeric),
  ('Thick Poha', 'Staples & Grains', 'kg', 45::numeric),
  ('Thin Poha', 'Staples & Grains', 'kg', 45::numeric),
  ('Rice Flakes', 'Staples & Grains', 'kg', 45::numeric),
  ('Sabudana', 'Staples & Grains', 'kg', 45::numeric),
  ('Quinoa', 'Staples & Grains', 'kg', 160::numeric),
  ('Rolled Oats', 'Staples & Grains', 'kg', 160::numeric),
  ('Instant Oats', 'Staples & Grains', 'kg', 160::numeric),
  ('Steel Cut Oats', 'Staples & Grains', 'kg', 160::numeric),
  ('Oats', 'Staples & Grains', 'kg', 160::numeric),
  ('Corn Flakes', 'Staples & Grains', 'piece', 120::numeric),
  ('Wheat Flakes', 'Staples & Grains', 'piece', 120::numeric),
  ('Muesli', 'Staples & Grains', 'piece', 120::numeric),
  ('Granola', 'Staples & Grains', 'piece', 120::numeric),
  ('Dalia', 'Staples & Grains', 'piece', 120::numeric),
  ('Broken Wheat', 'Staples & Grains', 'kg', 40::numeric),
  ('Semolina', 'Staples & Grains', 'kg', 40::numeric),
  ('Fine Suji', 'Staples & Grains', 'kg', 40::numeric),
  ('Rava', 'Staples & Grains', 'kg', 40::numeric),
  ('Maida', 'Staples & Grains', 'kg', 40::numeric),
  ('Whole Wheat Flour', 'Staples & Grains', 'kg', 48::numeric),
  ('Multigrain Atta', 'Staples & Grains', 'kg', 48::numeric),
  ('Bread Flour', 'Staples & Grains', 'kg', 48::numeric),
  ('All Purpose Flour', 'Staples & Grains', 'kg', 48::numeric),
  ('Besan', 'Staples & Grains', 'kg', 70::numeric),
  ('Gram Flour', 'Staples & Grains', 'kg', 70::numeric),
  ('Rice Flour', 'Staples & Grains', 'kg', 70::numeric),
  ('Corn Flour', 'Staples & Grains', 'kg', 70::numeric),
  ('Cornmeal', 'Staples & Grains', 'kg', 70::numeric),
  ('Ragi Flour', 'Staples & Grains', 'kg', 85::numeric),
  ('Jowar Flour', 'Staples & Grains', 'kg', 85::numeric),
  ('Bajra Flour', 'Staples & Grains', 'kg', 85::numeric),
  ('Barley Flour', 'Staples & Grains', 'kg', 85::numeric),
  ('Millet Flour', 'Staples & Grains', 'kg', 85::numeric),
  ('Buckwheat Flour', 'Staples & Grains', 'kg', 85::numeric),
  ('Rajgira Flour', 'Staples & Grains', 'kg', 85::numeric),
  ('Soy Flour', 'Staples & Grains', 'kg', 85::numeric),
  ('Almond Flour', 'Staples & Grains', 'kg', 85::numeric),
  ('Coconut Flour', 'Staples & Grains', 'kg', 85::numeric),
  ('Toor Dal', 'Pulses, Dal & Beans', 'kg', 150::numeric),
  ('Arhar Dal', 'Pulses, Dal & Beans', 'kg', 150::numeric),
  ('Moong Dal', 'Pulses, Dal & Beans', 'kg', 150::numeric),
  ('Yellow Moong Dal', 'Pulses, Dal & Beans', 'kg', 150::numeric),
  ('Green Moong Dal', 'Pulses, Dal & Beans', 'kg', 150::numeric),
  ('Whole Green Moong', 'Pulses, Dal & Beans', 'kg', 150::numeric),
  ('Masoor Dal', 'Pulses, Dal & Beans', 'kg', 150::numeric),
  ('Whole Masoor', 'Pulses, Dal & Beans', 'kg', 150::numeric),
  ('Red Lentils', 'Pulses, Dal & Beans', 'kg', 150::numeric),
  ('Urad Dal', 'Pulses, Dal & Beans', 'kg', 130::numeric),
  ('Whole Urad Dal', 'Pulses, Dal & Beans', 'kg', 130::numeric),
  ('Dhuli Urad Dal', 'Pulses, Dal & Beans', 'kg', 130::numeric),
  ('Chana Dal', 'Pulses, Dal & Beans', 'kg', 130::numeric),
  ('Kabuli Chana', 'Pulses, Dal & Beans', 'kg', 130::numeric),
  ('Kala Chana', 'Pulses, Dal & Beans', 'kg', 130::numeric),
  ('Horse Gram', 'Pulses, Dal & Beans', 'kg', 130::numeric),
  ('Moth Dal', 'Pulses, Dal & Beans', 'kg', 130::numeric),
  ('Moth Beans', 'Pulses, Dal & Beans', 'kg', 130::numeric),
  ('Rajma', 'Pulses, Dal & Beans', 'kg', 180::numeric),
  ('Kashmiri Rajma', 'Pulses, Dal & Beans', 'kg', 180::numeric),
  ('Black Rajma', 'Pulses, Dal & Beans', 'kg', 180::numeric),
  ('Black Beans', 'Pulses, Dal & Beans', 'kg', 180::numeric),
  ('Pinto Beans', 'Pulses, Dal & Beans', 'kg', 180::numeric),
  ('Kidney Beans', 'Pulses, Dal & Beans', 'kg', 180::numeric),
  ('Adzuki Beans', 'Pulses, Dal & Beans', 'kg', 180::numeric),
  ('Fava Beans', 'Pulses, Dal & Beans', 'kg', 180::numeric),
  ('Lima Beans', 'Pulses, Dal & Beans', 'kg', 180::numeric),
  ('Lobia', 'Pulses, Dal & Beans', 'kg', 80::numeric),
  ('White Peas', 'Pulses, Dal & Beans', 'kg', 80::numeric),
  ('Dried Green Peas', 'Pulses, Dal & Beans', 'kg', 80::numeric),
  ('Dried Yellow Peas', 'Pulses, Dal & Beans', 'kg', 80::numeric),
  ('Soybeans', 'Pulses, Dal & Beans', 'kg', 80::numeric),
  ('Black Eyed Peas', 'Pulses, Dal & Beans', 'kg', 80::numeric),
  ('Chickpeas', 'Pulses, Dal & Beans', 'kg', 80::numeric),
  ('Matki', 'Pulses, Dal & Beans', 'kg', 110::numeric),
  ('Mixed Dal', 'Pulses, Dal & Beans', 'kg', 110::numeric),
  ('Five Lentil Mix', 'Pulses, Dal & Beans', 'kg', 110::numeric),
  ('Sprouted Moong', 'Pulses, Dal & Beans', 'kg', 110::numeric),
  ('Sprouted Chana', 'Pulses, Dal & Beans', 'kg', 110::numeric),
  ('Green Lentils', 'Pulses, Dal & Beans', 'kg', 110::numeric),
  ('Sugar', 'Sugar, Salt & Sweeteners', 'kg', 45::numeric),
  ('Brown Sugar', 'Sugar, Salt & Sweeteners', 'kg', 45::numeric),
  ('Powdered Sugar', 'Sugar, Salt & Sweeteners', 'kg', 45::numeric),
  ('Icing Sugar', 'Sugar, Salt & Sweeteners', 'kg', 45::numeric),
  ('Table Salt', 'Sugar, Salt & Sweeteners', 'kg', 45::numeric),
  ('Iodized Salt', 'Sugar, Salt & Sweeteners', 'kg', 45::numeric),
  ('Sea Salt', 'Sugar, Salt & Sweeteners', 'kg', 45::numeric),
  ('Low Sodium Salt', 'Sugar, Salt & Sweeteners', 'kg', 45::numeric),
  ('Kosher Salt', 'Sugar, Salt & Sweeteners', 'kg', 45::numeric),
  ('Baking Salt', 'Sugar, Salt & Sweeteners', 'kg', 45::numeric),
  ('Salt Substitute', 'Sugar, Salt & Sweeteners', 'kg', 45::numeric),
  ('Jaggery', 'Sugar, Salt & Sweeteners', 'kg', 70::numeric),
  ('Jaggery Powder', 'Sugar, Salt & Sweeteners', 'kg', 70::numeric),
  ('Coconut Sugar', 'Sugar, Salt & Sweeteners', 'kg', 70::numeric),
  ('Palm Sugar', 'Sugar, Salt & Sweeteners', 'kg', 70::numeric),
  ('Rock Sugar', 'Sugar, Salt & Sweeteners', 'kg', 70::numeric),
  ('Mishri', 'Sugar, Salt & Sweeteners', 'kg', 70::numeric),
  ('Rock Salt', 'Sugar, Salt & Sweeteners', 'kg', 35::numeric),
  ('Himalayan Pink Salt', 'Sugar, Salt & Sweeteners', 'kg', 35::numeric),
  ('Black Salt', 'Sugar, Salt & Sweeteners', 'kg', 35::numeric),
  ('Sunflower Oil', 'Cooking Oils & Ghee', 'liter', 140::numeric),
  ('Soybean Oil', 'Cooking Oils & Ghee', 'liter', 140::numeric),
  ('Rice Bran Oil', 'Cooking Oils & Ghee', 'liter', 140::numeric),
  ('Vegetable Oil', 'Cooking Oils & Ghee', 'liter', 140::numeric),
  ('Corn Oil', 'Cooking Oils & Ghee', 'liter', 140::numeric),
  ('Safflower Oil', 'Cooking Oils & Ghee', 'liter', 140::numeric),
  ('Canola Oil', 'Cooking Oils & Ghee', 'liter', 140::numeric),
  ('Blended Cooking Oil', 'Cooking Oils & Ghee', 'liter', 140::numeric),
  ('Mustard Oil', 'Cooking Oils & Ghee', 'liter', 165::numeric),
  ('Groundnut Oil', 'Cooking Oils & Ghee', 'liter', 165::numeric),
  ('Coconut Oil', 'Cooking Oils & Ghee', 'liter', 165::numeric),
  ('Sesame Oil', 'Cooking Oils & Ghee', 'liter', 165::numeric),
  ('Palm Oil', 'Cooking Oils & Ghee', 'liter', 165::numeric),
  ('Flaxseed Oil', 'Cooking Oils & Ghee', 'liter', 165::numeric),
  ('Olive Oil', 'Cooking Oils & Ghee', 'liter', 320::numeric),
  ('Extra Virgin Olive Oil', 'Cooking Oils & Ghee', 'liter', 320::numeric),
  ('Pomace Olive Oil', 'Cooking Oils & Ghee', 'liter', 320::numeric),
  ('Avocado Oil', 'Cooking Oils & Ghee', 'liter', 320::numeric),
  ('Desi Ghee', 'Cooking Oils & Ghee', 'kg', 380::numeric),
  ('Cow Ghee', 'Cooking Oils & Ghee', 'kg', 380::numeric),
  ('Buffalo Ghee', 'Cooking Oils & Ghee', 'kg', 380::numeric),
  ('Organic Ghee', 'Cooking Oils & Ghee', 'kg', 380::numeric),
  ('Butter', 'Cooking Oils & Ghee', 'kg', 260::numeric),
  ('Salted Butter', 'Cooking Oils & Ghee', 'kg', 260::numeric),
  ('Unsalted Butter', 'Cooking Oils & Ghee', 'kg', 260::numeric),
  ('Clarified Butter', 'Cooking Oils & Ghee', 'kg', 260::numeric),
  ('Cooking Spray', 'Cooking Oils & Ghee', 'piece', 180::numeric),
  ('Olive Oil Spray', 'Cooking Oils & Ghee', 'piece', 180::numeric),
  ('Coconut Oil Spray', 'Cooking Oils & Ghee', 'piece', 180::numeric),
  ('Mustard Oil Bottle', 'Cooking Oils & Ghee', 'piece', 180::numeric),
  ('Turmeric Powder', 'Spices & Masalas', '100g', 55::numeric),
  ('Red Chilli Powder', 'Spices & Masalas', '100g', 55::numeric),
  ('Kashmiri Chilli Powder', 'Spices & Masalas', '100g', 55::numeric),
  ('Coriander Powder', 'Spices & Masalas', '100g', 55::numeric),
  ('Cumin Powder', 'Spices & Masalas', '100g', 55::numeric),
  ('Garam Masala', 'Spices & Masalas', '100g', 55::numeric),
  ('Chaat Masala', 'Spices & Masalas', '100g', 55::numeric),
  ('Black Pepper', 'Spices & Masalas', '100g', 180::numeric),
  ('White Pepper', 'Spices & Masalas', '100g', 180::numeric),
  ('Black Pepper Powder', 'Spices & Masalas', '100g', 180::numeric),
  ('Nutmeg', 'Spices & Masalas', '100g', 180::numeric),
  ('Mace', 'Spices & Masalas', '100g', 180::numeric),
  ('Cumin Seeds', 'Spices & Masalas', '100g', 40::numeric),
  ('Coriander Seeds', 'Spices & Masalas', '100g', 40::numeric),
  ('Fennel Seeds', 'Spices & Masalas', '100g', 40::numeric),
  ('Fenugreek Seeds', 'Spices & Masalas', '100g', 40::numeric),
  ('Mustard Seeds', 'Spices & Masalas', '100g', 40::numeric),
  ('Ajwain', 'Spices & Masalas', '100g', 40::numeric),
  ('Carom Seeds', 'Spices & Masalas', '100g', 40::numeric),
  ('Nigella Seeds', 'Spices & Masalas', '100g', 40::numeric),
  ('Sesame Seeds', 'Spices & Masalas', '100g', 40::numeric),
  ('Poppy Seeds', 'Spices & Masalas', '100g', 40::numeric),
  ('Cardamom', 'Spices & Masalas', '50g', 120::numeric),
  ('Green Cardamom', 'Spices & Masalas', '50g', 120::numeric),
  ('Black Cardamom', 'Spices & Masalas', '50g', 120::numeric),
  ('Cinnamon', 'Spices & Masalas', '50g', 120::numeric),
  ('Cloves', 'Spices & Masalas', '50g', 120::numeric),
  ('Bay Leaf', 'Spices & Masalas', '50g', 120::numeric),
  ('Star Anise', 'Spices & Masalas', '50g', 120::numeric),
  ('Dry Ginger Powder', 'Spices & Masalas', '100g', 65::numeric),
  ('Asafoetida', 'Spices & Masalas', '100g', 65::numeric),
  ('Kasuri Methi', 'Spices & Masalas', '100g', 65::numeric),
  ('Kitchen King Masala', 'Spices & Masalas', '100g', 70::numeric),
  ('Chicken Masala', 'Spices & Masalas', '100g', 70::numeric),
  ('Mutton Masala', 'Spices & Masalas', '100g', 70::numeric),
  ('Biryani Masala', 'Spices & Masalas', '100g', 70::numeric),
  ('Pav Bhaji Masala', 'Spices & Masalas', '100g', 70::numeric),
  ('Chole Masala', 'Spices & Masalas', '100g', 70::numeric),
  ('Rajma Masala', 'Spices & Masalas', '100g', 70::numeric),
  ('Sambar Powder', 'Spices & Masalas', '100g', 70::numeric),
  ('Rasam Powder', 'Spices & Masalas', '100g', 70::numeric),
  ('Curry Powder', 'Spices & Masalas', '100g', 70::numeric),
  ('Tandoori Masala', 'Spices & Masalas', '100g', 70::numeric),
  ('Fish Masala', 'Spices & Masalas', '100g', 70::numeric),
  ('Tea Masala', 'Spices & Masalas', '100g', 70::numeric),
  ('Paneer Masala', 'Spices & Masalas', '100g', 70::numeric),
  ('Sabzi Masala', 'Spices & Masalas', '100g', 70::numeric),
  ('Dal Tadka Masala', 'Spices & Masalas', '100g', 70::numeric),
  ('Pav Bhaji Spice', 'Spices & Masalas', '100g', 70::numeric),
  ('Peri Peri Seasoning', 'Spices & Masalas', '100g', 70::numeric),
  ('Tomato Ketchup', 'Sauces, Spreads & Condiments', 'piece', 75::numeric),
  ('Hot Tomato Ketchup', 'Sauces, Spreads & Condiments', 'piece', 75::numeric),
  ('Chilli Sauce', 'Sauces, Spreads & Condiments', 'piece', 75::numeric),
  ('Green Chilli Sauce', 'Sauces, Spreads & Condiments', 'piece', 75::numeric),
  ('Red Chilli Sauce', 'Sauces, Spreads & Condiments', 'piece', 75::numeric),
  ('Schezwan Sauce', 'Sauces, Spreads & Condiments', 'piece', 75::numeric),
  ('Soy Sauce', 'Sauces, Spreads & Condiments', 'piece', 75::numeric),
  ('Dark Soy Sauce', 'Sauces, Spreads & Condiments', 'piece', 75::numeric),
  ('Light Soy Sauce', 'Sauces, Spreads & Condiments', 'piece', 75::numeric),
  ('Vinegar', 'Sauces, Spreads & Condiments', 'piece', 75::numeric),
  ('Apple Cider Vinegar', 'Sauces, Spreads & Condiments', 'piece', 75::numeric),
  ('White Vinegar', 'Sauces, Spreads & Condiments', 'piece', 75::numeric),
  ('Balsamic Vinegar', 'Sauces, Spreads & Condiments', 'piece', 75::numeric),
  ('Mustard Sauce', 'Sauces, Spreads & Condiments', 'piece', 75::numeric),
  ('English Mustard', 'Sauces, Spreads & Condiments', 'piece', 75::numeric),
  ('Mayonnaise', 'Sauces, Spreads & Condiments', 'piece', 110::numeric),
  ('Eggless Mayonnaise', 'Sauces, Spreads & Condiments', 'piece', 110::numeric),
  ('Garlic Mayonnaise', 'Sauces, Spreads & Condiments', 'piece', 110::numeric),
  ('Mint Mayonnaise', 'Sauces, Spreads & Condiments', 'piece', 110::numeric),
  ('Thousand Island Dressing', 'Sauces, Spreads & Condiments', 'piece', 110::numeric),
  ('Ranch Dressing', 'Sauces, Spreads & Condiments', 'piece', 110::numeric),
  ('Salad Dressing', 'Sauces, Spreads & Condiments', 'piece', 110::numeric),
  ('Peanut Butter', 'Sauces, Spreads & Condiments', 'piece', 180::numeric),
  ('Crunchy Peanut Butter', 'Sauces, Spreads & Condiments', 'piece', 180::numeric),
  ('Smooth Peanut Butter', 'Sauces, Spreads & Condiments', 'piece', 180::numeric),
  ('Almond Butter', 'Sauces, Spreads & Condiments', 'piece', 180::numeric),
  ('Cashew Butter', 'Sauces, Spreads & Condiments', 'piece', 180::numeric),
  ('Chocolate Spread', 'Sauces, Spreads & Condiments', 'piece', 180::numeric),
  ('Strawberry Jam', 'Sauces, Spreads & Condiments', 'piece', 95::numeric),
  ('Mixed Fruit Jam', 'Sauces, Spreads & Condiments', 'piece', 95::numeric),
  ('Mango Jam', 'Sauces, Spreads & Condiments', 'piece', 95::numeric),
  ('Orange Marmalade', 'Sauces, Spreads & Condiments', 'piece', 95::numeric),
  ('Honey', 'Sauces, Spreads & Condiments', 'piece', 95::numeric),
  ('Organic Honey', 'Sauces, Spreads & Condiments', 'piece', 95::numeric),
  ('Maple Syrup', 'Sauces, Spreads & Condiments', 'piece', 95::numeric),
  ('Date Syrup', 'Sauces, Spreads & Condiments', 'piece', 95::numeric),
  ('Chilli Pickle', 'Sauces, Spreads & Condiments', 'piece', 65::numeric),
  ('Mango Pickle', 'Sauces, Spreads & Condiments', 'piece', 65::numeric),
  ('Lemon Pickle', 'Sauces, Spreads & Condiments', 'piece', 65::numeric),
  ('Mixed Pickle', 'Sauces, Spreads & Condiments', 'piece', 65::numeric),
  ('Marie Biscuits', 'Biscuits, Cookies & Crackers', 'piece', 30::numeric),
  ('Glucose Biscuits', 'Biscuits, Cookies & Crackers', 'piece', 30::numeric),
  ('Salted Biscuits', 'Biscuits, Cookies & Crackers', 'piece', 30::numeric),
  ('Salt Crackers', 'Biscuits, Cookies & Crackers', 'piece', 30::numeric),
  ('Cream Crackers', 'Biscuits, Cookies & Crackers', 'piece', 30::numeric),
  ('Jeera Biscuits', 'Biscuits, Cookies & Crackers', 'piece', 30::numeric),
  ('Digestive Biscuits', 'Biscuits, Cookies & Crackers', 'piece', 45::numeric),
  ('Cream Biscuits', 'Biscuits, Cookies & Crackers', 'piece', 45::numeric),
  ('Chocolate Cream Biscuits', 'Biscuits, Cookies & Crackers', 'piece', 45::numeric),
  ('Bourbon Biscuits', 'Biscuits, Cookies & Crackers', 'piece', 45::numeric),
  ('Chocolate Biscuits', 'Biscuits, Cookies & Crackers', 'piece', 45::numeric),
  ('Oat Cookies', 'Biscuits, Cookies & Crackers', 'piece', 45::numeric),
  ('Almond Cookies', 'Biscuits, Cookies & Crackers', 'piece', 45::numeric),
  ('Cashew Cookies', 'Biscuits, Cookies & Crackers', 'piece', 45::numeric),
  ('Shortbread Cookies', 'Biscuits, Cookies & Crackers', 'piece', 45::numeric),
  ('Chocolate Chip Cookies', 'Biscuits, Cookies & Crackers', 'piece', 45::numeric),
  ('Ginger Cookies', 'Biscuits, Cookies & Crackers', 'piece', 45::numeric),
  ('Coconut Cookies', 'Biscuits, Cookies & Crackers', 'piece', 45::numeric),
  ('Butter Cookies', 'Biscuits, Cookies & Crackers', 'piece', 50::numeric),
  ('Multigrain Biscuits', 'Biscuits, Cookies & Crackers', 'piece', 50::numeric),
  ('Sugar-Free Biscuits', 'Biscuits, Cookies & Crackers', 'piece', 50::numeric),
  ('Ragi Biscuits', 'Biscuits, Cookies & Crackers', 'piece', 50::numeric),
  ('Digestive Oat Biscuits', 'Biscuits, Cookies & Crackers', 'piece', 50::numeric),
  ('Wafer Biscuits', 'Biscuits, Cookies & Crackers', 'piece', 50::numeric),
  ('Cheese Crackers', 'Biscuits, Cookies & Crackers', 'piece', 50::numeric),
  ('Potato Chips', 'Chips, Namkeen & Snacks', 'piece', 25::numeric),
  ('Salted Potato Chips', 'Chips, Namkeen & Snacks', 'piece', 25::numeric),
  ('Masala Potato Chips', 'Chips, Namkeen & Snacks', 'piece', 25::numeric),
  ('Peri Peri Chips', 'Chips, Namkeen & Snacks', 'piece', 25::numeric),
  ('Banana Chips', 'Chips, Namkeen & Snacks', 'piece', 25::numeric),
  ('Tapioca Chips', 'Chips, Namkeen & Snacks', 'piece', 25::numeric),
  ('Popcorn', 'Chips, Namkeen & Snacks', 'piece', 25::numeric),
  ('Salted Popcorn', 'Chips, Namkeen & Snacks', 'piece', 25::numeric),
  ('Butter Popcorn', 'Chips, Namkeen & Snacks', 'piece', 25::numeric),
  ('Caramel Popcorn', 'Chips, Namkeen & Snacks', 'piece', 25::numeric),
  ('Microwave Popcorn', 'Chips, Namkeen & Snacks', 'piece', 25::numeric),
  ('Nachos', 'Chips, Namkeen & Snacks', 'piece', 55::numeric),
  ('Cheese Nachos', 'Chips, Namkeen & Snacks', 'piece', 55::numeric),
  ('Tortilla Chips', 'Chips, Namkeen & Snacks', 'piece', 55::numeric),
  ('Bhujia', 'Chips, Namkeen & Snacks', 'piece', 35::numeric),
  ('Aloo Bhujia', 'Chips, Namkeen & Snacks', 'piece', 35::numeric),
  ('Sev', 'Chips, Namkeen & Snacks', 'piece', 35::numeric),
  ('Nylon Sev', 'Chips, Namkeen & Snacks', 'piece', 35::numeric),
  ('Mixture', 'Chips, Namkeen & Snacks', 'piece', 35::numeric),
  ('Bombay Mix', 'Chips, Namkeen & Snacks', 'piece', 35::numeric),
  ('Bikaneri Mixture', 'Chips, Namkeen & Snacks', 'piece', 35::numeric),
  ('Moong Dal Namkeen', 'Chips, Namkeen & Snacks', 'piece', 35::numeric),
  ('Chana Dal Namkeen', 'Chips, Namkeen & Snacks', 'piece', 35::numeric),
  ('Peanuts', 'Chips, Namkeen & Snacks', 'piece', 45::numeric),
  ('Masala Peanuts', 'Chips, Namkeen & Snacks', 'piece', 45::numeric),
  ('Roasted Chana', 'Chips, Namkeen & Snacks', 'piece', 45::numeric),
  ('Roasted Makhana', 'Chips, Namkeen & Snacks', 'piece', 45::numeric),
  ('Salted Makhana', 'Chips, Namkeen & Snacks', 'piece', 45::numeric),
  ('Trail Mix', 'Chips, Namkeen & Snacks', 'piece', 45::numeric),
  ('Protein Snack Mix', 'Chips, Namkeen & Snacks', 'piece', 45::numeric),
  ('Chocolate Corn Flakes', 'Breakfast & Cereals', 'piece', 110::numeric),
  ('Honey Corn Flakes', 'Breakfast & Cereals', 'piece', 110::numeric),
  ('Chocos', 'Breakfast & Cereals', 'piece', 110::numeric),
  ('Fruit & Nut Muesli', 'Breakfast & Cereals', 'piece', 110::numeric),
  ('Chocolate Muesli', 'Breakfast & Cereals', 'piece', 110::numeric),
  ('Oats Muesli', 'Breakfast & Cereals', 'piece', 110::numeric),
  ('Honey Granola', 'Breakfast & Cereals', 'piece', 110::numeric),
  ('Protein Granola', 'Breakfast & Cereals', 'piece', 110::numeric),
  ('Bran Flakes', 'Breakfast & Cereals', 'piece', 110::numeric),
  ('Instant Poha', 'Breakfast & Cereals', 'piece', 65::numeric),
  ('Instant Upma', 'Breakfast & Cereals', 'piece', 65::numeric),
  ('Instant Oats', 'Breakfast & Cereals', 'piece', 65::numeric),
  ('Masala Oats', 'Breakfast & Cereals', 'piece', 65::numeric),
  ('Plain Oats', 'Breakfast & Cereals', 'piece', 65::numeric),
  ('Pancake Mix', 'Breakfast & Cereals', 'piece', 140::numeric),
  ('Waffle Mix', 'Breakfast & Cereals', 'piece', 140::numeric),
  ('Chocolate Pancake Mix', 'Breakfast & Cereals', 'piece', 140::numeric),
  ('Breakfast Cereal Mix', 'Breakfast & Cereals', 'piece', 140::numeric),
  ('Instant Noodles', 'Noodles, Pasta & Instant Food', 'piece', 30::numeric),
  ('Masala Noodles', 'Noodles, Pasta & Instant Food', 'piece', 30::numeric),
  ('Chicken Noodles', 'Noodles, Pasta & Instant Food', 'piece', 30::numeric),
  ('Cup Noodles', 'Noodles, Pasta & Instant Food', 'piece', 30::numeric),
  ('Rice Noodles', 'Noodles, Pasta & Instant Food', 'piece', 30::numeric),
  ('Hakka Noodles', 'Noodles, Pasta & Instant Food', 'piece', 30::numeric),
  ('Schezwan Noodles', 'Noodles, Pasta & Instant Food', 'piece', 30::numeric),
  ('Instant Ramen', 'Noodles, Pasta & Instant Food', 'piece', 30::numeric),
  ('Spaghetti', 'Noodles, Pasta & Instant Food', 'piece', 70::numeric),
  ('Penne Pasta', 'Noodles, Pasta & Instant Food', 'piece', 70::numeric),
  ('Fusilli Pasta', 'Noodles, Pasta & Instant Food', 'piece', 70::numeric),
  ('Macaroni', 'Noodles, Pasta & Instant Food', 'piece', 70::numeric),
  ('Farfalle Pasta', 'Noodles, Pasta & Instant Food', 'piece', 70::numeric),
  ('Lasagne Sheets', 'Noodles, Pasta & Instant Food', 'piece', 70::numeric),
  ('Whole Wheat Pasta', 'Noodles, Pasta & Instant Food', 'piece', 70::numeric),
  ('Multigrain Pasta', 'Noodles, Pasta & Instant Food', 'piece', 70::numeric),
  ('Vermicelli', 'Noodles, Pasta & Instant Food', 'piece', 70::numeric),
  ('Rice Vermicelli', 'Noodles, Pasta & Instant Food', 'piece', 70::numeric),
  ('Instant Pasta', 'Noodles, Pasta & Instant Food', 'piece', 70::numeric),
  ('Mac & Cheese', 'Noodles, Pasta & Instant Food', 'piece', 70::numeric),
  ('Pasta Sauce', 'Noodles, Pasta & Instant Food', 'piece', 95::numeric),
  ('Tomato Pasta Sauce', 'Noodles, Pasta & Instant Food', 'piece', 95::numeric),
  ('Arrabbiata Sauce', 'Noodles, Pasta & Instant Food', 'piece', 95::numeric),
  ('Alfredo Sauce', 'Noodles, Pasta & Instant Food', 'piece', 95::numeric),
  ('Pesto Sauce', 'Noodles, Pasta & Instant Food', 'piece', 95::numeric),
  ('Assam Tea', 'Tea, Coffee & Hot Drinks', '100g', 65::numeric),
  ('Darjeeling Tea', 'Tea, Coffee & Hot Drinks', '100g', 65::numeric),
  ('Green Tea', 'Tea, Coffee & Hot Drinks', '100g', 65::numeric),
  ('Black Tea', 'Tea, Coffee & Hot Drinks', '100g', 65::numeric),
  ('Masala Tea', 'Tea, Coffee & Hot Drinks', '100g', 65::numeric),
  ('Ginger Tea', 'Tea, Coffee & Hot Drinks', '100g', 65::numeric),
  ('Lemon Tea', 'Tea, Coffee & Hot Drinks', '100g', 65::numeric),
  ('Herbal Tea', 'Tea, Coffee & Hot Drinks', '100g', 65::numeric),
  ('Chamomile Tea', 'Tea, Coffee & Hot Drinks', '100g', 65::numeric),
  ('Peppermint Tea', 'Tea, Coffee & Hot Drinks', '100g', 65::numeric),
  ('Earl Grey Tea', 'Tea, Coffee & Hot Drinks', '100g', 65::numeric),
  ('English Breakfast Tea', 'Tea, Coffee & Hot Drinks', '100g', 65::numeric),
  ('Instant Coffee', 'Tea, Coffee & Hot Drinks', '100g', 180::numeric),
  ('Filter Coffee', 'Tea, Coffee & Hot Drinks', '100g', 180::numeric),
  ('Ground Coffee', 'Tea, Coffee & Hot Drinks', '100g', 180::numeric),
  ('Arabica Coffee', 'Tea, Coffee & Hot Drinks', '100g', 180::numeric),
  ('Robusta Coffee', 'Tea, Coffee & Hot Drinks', '100g', 180::numeric),
  ('Cold Brew Coffee', 'Tea, Coffee & Hot Drinks', '100g', 180::numeric),
  ('Coffee Beans', 'Tea, Coffee & Hot Drinks', '100g', 180::numeric),
  ('Hot Chocolate Powder', 'Tea, Coffee & Hot Drinks', 'piece', 120::numeric),
  ('Mineral Water', 'Beverages', 'liter', 20::numeric),
  ('Sparkling Water', 'Beverages', 'liter', 20::numeric),
  ('Coconut Water', 'Beverages', 'liter', 20::numeric),
  ('Orange Juice', 'Beverages', 'liter', 65::numeric),
  ('Apple Juice', 'Beverages', 'liter', 65::numeric),
  ('Mango Juice', 'Beverages', 'liter', 65::numeric),
  ('Mixed Fruit Juice', 'Beverages', 'liter', 65::numeric),
  ('Pineapple Juice', 'Beverages', 'liter', 65::numeric),
  ('Cranberry Juice', 'Beverages', 'liter', 65::numeric),
  ('Tomato Juice', 'Beverages', 'liter', 65::numeric),
  ('Lemonade', 'Beverages', 'liter', 65::numeric),
  ('Iced Tea', 'Beverages', 'liter', 65::numeric),
  ('Cold Coffee', 'Beverages', 'piece', 80::numeric),
  ('Chocolate Milk', 'Beverages', 'piece', 80::numeric),
  ('Milkshake', 'Beverages', 'piece', 80::numeric),
  ('Energy Drink', 'Beverages', 'piece', 55::numeric),
  ('Sports Drink', 'Beverages', 'piece', 55::numeric),
  ('Electrolyte Drink', 'Beverages', 'piece', 55::numeric),
  ('Ginger Ale', 'Beverages', 'piece', 55::numeric),
  ('Tonic Water', 'Beverages', 'piece', 55::numeric),
  ('Full Cream Milk', 'Dairy & Eggs', 'liter', 28::numeric),
  ('Toned Milk', 'Dairy & Eggs', 'liter', 28::numeric),
  ('Double Toned Milk', 'Dairy & Eggs', 'liter', 28::numeric),
  ('Skimmed Milk', 'Dairy & Eggs', 'liter', 28::numeric),
  ('A2 Milk', 'Dairy & Eggs', 'liter', 28::numeric),
  ('Organic Milk', 'Dairy & Eggs', 'liter', 28::numeric),
  ('Soy Milk', 'Dairy & Eggs', 'liter', 55::numeric),
  ('Almond Milk', 'Dairy & Eggs', 'liter', 55::numeric),
  ('Oat Milk', 'Dairy & Eggs', 'liter', 55::numeric),
  ('Coconut Milk', 'Dairy & Eggs', 'liter', 55::numeric),
  ('Buttermilk', 'Dairy & Eggs', 'piece', 35::numeric),
  ('Lassi', 'Dairy & Eggs', 'piece', 35::numeric),
  ('Sweet Lassi', 'Dairy & Eggs', 'piece', 35::numeric),
  ('Salted Lassi', 'Dairy & Eggs', 'piece', 35::numeric),
  ('Curd', 'Dairy & Eggs', 'piece', 45::numeric),
  ('Greek Yogurt', 'Dairy & Eggs', 'piece', 45::numeric),
  ('Plain Yogurt', 'Dairy & Eggs', 'piece', 45::numeric),
  ('Flavored Yogurt', 'Dairy & Eggs', 'piece', 45::numeric),
  ('Strawberry Yogurt', 'Dairy & Eggs', 'piece', 45::numeric),
  ('Mango Yogurt', 'Dairy & Eggs', 'piece', 45::numeric),
  ('Paneer', 'Dairy & Eggs', 'piece', 75::numeric),
  ('Low Fat Paneer', 'Dairy & Eggs', 'piece', 75::numeric),
  ('Tofu', 'Dairy & Eggs', 'piece', 75::numeric),
  ('Cheddar Cheese', 'Dairy & Eggs', 'piece', 120::numeric),
  ('Mozzarella Cheese', 'Dairy & Eggs', 'piece', 120::numeric),
  ('Processed Cheese', 'Dairy & Eggs', 'piece', 120::numeric),
  ('Cheese Slices', 'Dairy & Eggs', 'piece', 120::numeric),
  ('Cream Cheese', 'Dairy & Eggs', 'piece', 120::numeric),
  ('Parmesan Cheese', 'Dairy & Eggs', 'piece', 120::numeric),
  ('Eggs', 'Dairy & Eggs', 'dozen', 72::numeric),
  ('Almonds', 'Dry Fruits & Nuts', '200g', 320::numeric),
  ('Cashews', 'Dry Fruits & Nuts', '200g', 320::numeric),
  ('Walnuts', 'Dry Fruits & Nuts', '200g', 320::numeric),
  ('Pistachios', 'Dry Fruits & Nuts', '200g', 320::numeric),
  ('Hazelnuts', 'Dry Fruits & Nuts', '200g', 320::numeric),
  ('Pecans', 'Dry Fruits & Nuts', '200g', 320::numeric),
  ('Macadamia Nuts', 'Dry Fruits & Nuts', '200g', 320::numeric),
  ('Brazil Nuts', 'Dry Fruits & Nuts', '200g', 320::numeric),
  ('Pine Nuts', 'Dry Fruits & Nuts', '200g', 320::numeric),
  ('Peanuts', 'Dry Fruits & Nuts', '200g', 140::numeric),
  ('Raisins', 'Dry Fruits & Nuts', '200g', 140::numeric),
  ('Black Raisins', 'Dry Fruits & Nuts', '200g', 140::numeric),
  ('Golden Raisins', 'Dry Fruits & Nuts', '200g', 140::numeric),
  ('Dates', 'Dry Fruits & Nuts', '200g', 140::numeric),
  ('Dried Figs', 'Dry Fruits & Nuts', '200g', 140::numeric),
  ('Dried Apricots', 'Dry Fruits & Nuts', '200g', 140::numeric),
  ('Dried Cranberries', 'Dry Fruits & Nuts', '200g', 140::numeric),
  ('Dried Blueberries', 'Dry Fruits & Nuts', '200g', 140::numeric),
  ('Dried Mango', 'Dry Fruits & Nuts', '200g', 140::numeric),
  ('Dried Coconut', 'Dry Fruits & Nuts', '200g', 140::numeric),
  ('Chia Seeds', 'Dry Fruits & Nuts', '200g', 180::numeric),
  ('Flax Seeds', 'Dry Fruits & Nuts', '200g', 180::numeric),
  ('Pumpkin Seeds', 'Dry Fruits & Nuts', '200g', 180::numeric),
  ('Sunflower Seeds', 'Dry Fruits & Nuts', '200g', 180::numeric),
  ('Hemp Seeds', 'Dry Fruits & Nuts', '200g', 180::numeric),
  ('White Bread', 'Bakery, Ready-to-Eat & Misc', 'piece', 35::numeric),
  ('Brown Bread', 'Bakery, Ready-to-Eat & Misc', 'piece', 35::numeric),
  ('Multigrain Bread', 'Bakery, Ready-to-Eat & Misc', 'piece', 35::numeric),
  ('Whole Wheat Bread', 'Bakery, Ready-to-Eat & Misc', 'piece', 35::numeric),
  ('Sandwich Bread', 'Bakery, Ready-to-Eat & Misc', 'piece', 35::numeric),
  ('Pav', 'Bakery, Ready-to-Eat & Misc', 'piece', 35::numeric),
  ('Garlic Bread', 'Bakery, Ready-to-Eat & Misc', 'piece', 65::numeric),
  ('Burger Buns', 'Bakery, Ready-to-Eat & Misc', 'piece', 65::numeric),
  ('Hot Dog Buns', 'Bakery, Ready-to-Eat & Misc', 'piece', 65::numeric),
  ('Pizza Base', 'Bakery, Ready-to-Eat & Misc', 'piece', 65::numeric),
  ('Tortilla Wraps', 'Bakery, Ready-to-Eat & Misc', 'piece', 65::numeric),
  ('Roti', 'Bakery, Ready-to-Eat & Misc', 'piece', 45::numeric),
  ('Paratha', 'Bakery, Ready-to-Eat & Misc', 'piece', 45::numeric),
  ('Frozen Paratha', 'Bakery, Ready-to-Eat & Misc', 'piece', 45::numeric),
  ('Frozen Peas', 'Bakery, Ready-to-Eat & Misc', 'piece', 45::numeric),
  ('Frozen Corn', 'Bakery, Ready-to-Eat & Misc', 'piece', 45::numeric),
  ('Frozen Mixed Vegetables', 'Bakery, Ready-to-Eat & Misc', 'piece', 45::numeric),
  ('Frozen French Fries', 'Bakery, Ready-to-Eat & Misc', 'piece', 45::numeric),
  ('Frozen Samosa', 'Bakery, Ready-to-Eat & Misc', 'piece', 45::numeric),
  ('Frozen Spring Rolls', 'Bakery, Ready-to-Eat & Misc', 'piece', 45::numeric),
  ('Croissant', 'Bakery, Ready-to-Eat & Misc', 'piece', 55::numeric),
  ('Instant Idli Mix', 'Bakery, Ready-to-Eat & Misc', 'piece', 55::numeric),
  ('Instant Dosa Mix', 'Bakery, Ready-to-Eat & Misc', 'piece', 55::numeric),
  ('Papad', 'Bakery, Ready-to-Eat & Misc', 'piece', 55::numeric),
  ('Coconut Milk Powder', 'Bakery, Ready-to-Eat & Misc', 'piece', 55::numeric),
  ('Potato', 'Root vegetables', 'kg', 42::numeric),
  ('Baby Potato', 'Root vegetables', 'kg', 42::numeric),
  ('Sweet Potato', 'Root vegetables', 'kg', 42::numeric),
  ('Purple Sweet Potato', 'Root vegetables', 'kg', 42::numeric),
  ('Sweet Potato White', 'Root vegetables', 'kg', 42::numeric),
  ('Sweet Potato Orange', 'Root vegetables', 'kg', 42::numeric),
  ('Sweet Potato Purple', 'Root vegetables', 'kg', 42::numeric),
  ('Air Potato', 'Root vegetables', 'kg', 42::numeric),
  ('Yam', 'Root vegetables', 'kg', 55::numeric),
  ('Elephant Foot Yam', 'Root vegetables', 'kg', 55::numeric),
  ('Purple Yam', 'Root vegetables', 'kg', 55::numeric),
  ('White Yam', 'Root vegetables', 'kg', 55::numeric),
  ('Chinese Yam', 'Root vegetables', 'kg', 55::numeric),
  ('Lesser Yam', 'Root vegetables', 'kg', 55::numeric),
  ('Greater Yam', 'Root vegetables', 'kg', 55::numeric),
  ('Suran', 'Root vegetables', 'kg', 55::numeric),
  ('Arbi', 'Root vegetables', 'kg', 55::numeric),
  ('Jimikand', 'Root vegetables', 'kg', 55::numeric),
  ('Kachalu', 'Root vegetables', 'kg', 55::numeric),
  ('Tapioca', 'Root vegetables', 'kg', 60::numeric),
  ('Cassava', 'Root vegetables', 'kg', 60::numeric),
  ('Arrowroot', 'Root vegetables', 'kg', 60::numeric),
  ('Taro Root', 'Root vegetables', 'kg', 60::numeric),
  ('Colocasia Root', 'Root vegetables', 'kg', 60::numeric),
  ('Carrot', 'Root vegetables', 'kg', 45::numeric),
  ('Baby Carrot', 'Root vegetables', 'kg', 45::numeric),
  ('Red Carrot', 'Root vegetables', 'kg', 45::numeric),
  ('Black Carrot', 'Root vegetables', 'kg', 45::numeric),
  ('Beetroot', 'Root vegetables', 'kg', 45::numeric),
  ('Golden Beetroot', 'Root vegetables', 'kg', 45::numeric),
  ('Beetroot Red', 'Root vegetables', 'kg', 45::numeric),
  ('Beetroot Golden', 'Root vegetables', 'kg', 45::numeric),
  ('Beetroot Chioggia', 'Root vegetables', 'kg', 45::numeric),
  ('Radish', 'Root vegetables', 'kg', 38::numeric),
  ('White Radish', 'Root vegetables', 'kg', 38::numeric),
  ('Red Radish', 'Root vegetables', 'kg', 38::numeric),
  ('Daikon', 'Root vegetables', 'kg', 38::numeric),
  ('Turnip', 'Root vegetables', 'kg', 38::numeric),
  ('Japanese Turnip', 'Root vegetables', 'kg', 38::numeric),
  ('Kohlrabi', 'Root vegetables', 'kg', 38::numeric),
  ('Parsnip', 'Root vegetables', 'kg', 38::numeric),
  ('Rutabaga', 'Root vegetables', 'kg', 38::numeric),
  ('Celeriac', 'Root vegetables', 'kg', 38::numeric),
  ('Jerusalem Artichoke', 'Root vegetables', 'kg', 38::numeric),
  ('Onion', 'Onions and bulbs', 'kg', 38::numeric),
  ('Red Onion', 'Onions and bulbs', 'kg', 38::numeric),
  ('White Onion', 'Onions and bulbs', 'kg', 38::numeric),
  ('Spring Onion', 'Onions and bulbs', 'kg', 38::numeric),
  ('Shallot', 'Onions and bulbs', 'kg', 38::numeric),
  ('Baby Onion', 'Onions and bulbs', 'kg', 38::numeric),
  ('Pearl Onion', 'Onions and bulbs', 'kg', 38::numeric),
  ('Sambar Onion', 'Onions and bulbs', 'kg', 38::numeric),
  ('Garlic', 'Onions and bulbs', 'kg', 120::numeric),
  ('Green Garlic', 'Onions and bulbs', 'kg', 120::numeric),
  ('Fresh Garlic', 'Onions and bulbs', 'kg', 120::numeric),
  ('Garlic Flakes', 'Onions and bulbs', 'kg', 120::numeric),
  ('Garlic Paste', 'Onions and bulbs', 'kg', 120::numeric),
  ('Ginger Garlic Mix', 'Onions and bulbs', 'kg', 120::numeric),
  ('Ginger', 'Onions and bulbs', 'kg', 90::numeric),
  ('Raw Turmeric', 'Onions and bulbs', 'kg', 90::numeric),
  ('Leek', 'Onions and bulbs', 'kg', 90::numeric),
  ('Fennel', 'Onions and bulbs', 'kg', 90::numeric),
  ('Fennel Bulb', 'Onions and bulbs', 'kg', 90::numeric),
  ('Tomato', 'Tomatoes', 'kg', 48::numeric),
  ('Cherry Tomato', 'Tomatoes', 'kg', 48::numeric),
  ('Roma Tomato', 'Tomatoes', 'kg', 48::numeric),
  ('Green Tomato', 'Tomatoes', 'kg', 48::numeric),
  ('Yellow Tomato', 'Tomatoes', 'kg', 48::numeric),
  ('Heirloom Tomato', 'Tomatoes', 'kg', 48::numeric),
  ('Beefsteak Tomato', 'Tomatoes', 'kg', 48::numeric),
  ('Plum Tomato', 'Tomatoes', 'kg', 48::numeric),
  ('Grape Tomato', 'Tomatoes', 'kg', 48::numeric),
  ('Yellow Cherry Tomato', 'Tomatoes', 'kg', 48::numeric),
  ('Green Cherry Tomato', 'Tomatoes', 'kg', 48::numeric),
  ('Desi Tomato', 'Tomatoes', 'kg', 48::numeric),
  ('Hybrid Tomato', 'Tomatoes', 'kg', 48::numeric),
  ('Cocktail Tomato', 'Tomatoes', 'kg', 48::numeric),
  ('Brinjal', 'Eggplant and okra', 'kg', 50::numeric),
  ('Round Brinjal', 'Eggplant and okra', 'kg', 50::numeric),
  ('Long Brinjal', 'Eggplant and okra', 'kg', 50::numeric),
  ('Green Brinjal', 'Eggplant and okra', 'kg', 50::numeric),
  ('Purple Brinjal', 'Eggplant and okra', 'kg', 50::numeric),
  ('White Brinjal', 'Eggplant and okra', 'kg', 50::numeric),
  ('Chinese Eggplant', 'Eggplant and okra', 'kg', 50::numeric),
  ('Thai Eggplant', 'Eggplant and okra', 'kg', 50::numeric),
  ('Japanese Eggplant', 'Eggplant and okra', 'kg', 50::numeric),
  ('Okra', 'Eggplant and okra', 'kg', 50::numeric),
  ('Red Okra', 'Eggplant and okra', 'kg', 50::numeric),
  ('Ladies Finger', 'Eggplant and okra', 'kg', 50::numeric),
  ('Bhindi Tender', 'Eggplant and okra', 'kg', 50::numeric),
  ('Bell Pepper', 'Capsicum and peppers', '500g', 68::numeric),
  ('Green Capsicum', 'Capsicum and peppers', '500g', 68::numeric),
  ('Red Capsicum', 'Capsicum and peppers', '500g', 68::numeric),
  ('Yellow Capsicum', 'Capsicum and peppers', '500g', 68::numeric),
  ('Orange Capsicum', 'Capsicum and peppers', '500g', 68::numeric),
  ('Mini Capsicum', 'Capsicum and peppers', '500g', 68::numeric),
  ('Green Peppers', 'Capsicum and peppers', '500g', 68::numeric),
  ('Red Peppers', 'Capsicum and peppers', '500g', 68::numeric),
  ('Yellow Peppers', 'Capsicum and peppers', '500g', 68::numeric),
  ('Green Chilli', 'Capsicum and peppers', '500g', 55::numeric),
  ('Red Chilli', 'Capsicum and peppers', '500g', 55::numeric),
  ('Jalapeno', 'Capsicum and peppers', '500g', 55::numeric),
  ('Banana Pepper', 'Capsicum and peppers', '500g', 55::numeric),
  ('Poblano Pepper', 'Capsicum and peppers', '500g', 55::numeric),
  ('Serrano Pepper', 'Capsicum and peppers', '500g', 55::numeric),
  ('Habanero Pepper', 'Capsicum and peppers', '500g', 55::numeric),
  ('Thai Chilli', 'Capsicum and peppers', '500g', 55::numeric),
  ('Long Pepper', 'Capsicum and peppers', '500g', 55::numeric),
  ('Green Paprika', 'Capsicum and peppers', '500g', 55::numeric),
  ('Cucumber', 'Cucumbers and salad', 'kg', 44::numeric),
  ('English Cucumber', 'Cucumbers and salad', 'kg', 44::numeric),
  ('Small Cucumber', 'Cucumbers and salad', 'kg', 44::numeric),
  ('Kakdi', 'Cucumbers and salad', 'kg', 44::numeric),
  ('Mini Cucumber', 'Cucumbers and salad', 'kg', 44::numeric),
  ('Persian Cucumber', 'Cucumbers and salad', 'kg', 44::numeric),
  ('Lebanese Cucumber', 'Cucumbers and salad', 'kg', 44::numeric),
  ('Japanese Cucumber', 'Cucumbers and salad', 'kg', 44::numeric),
  ('White Cucumber', 'Cucumbers and salad', 'kg', 44::numeric),
  ('Salad Cucumber', 'Cucumbers and salad', 'kg', 44::numeric),
  ('Zucchini', 'Cucumbers and salad', 'kg', 75::numeric),
  ('Yellow Zucchini', 'Cucumbers and salad', 'kg', 75::numeric),
  ('Yellow Squash', 'Cucumbers and salad', 'kg', 75::numeric),
  ('Chayote', 'Cucumbers and salad', 'kg', 75::numeric),
  ('Bottle Gourd', 'Gourds and squash', 'kg', 46::numeric),
  ('Round Bottle Gourd', 'Gourds and squash', 'kg', 46::numeric),
  ('Ridge Gourd', 'Gourds and squash', 'kg', 46::numeric),
  ('Sponge Gourd', 'Gourds and squash', 'kg', 46::numeric),
  ('Snake Gourd', 'Gourds and squash', 'kg', 46::numeric),
  ('Bitter Gourd', 'Gourds and squash', 'kg', 46::numeric),
  ('Baby Bitter Gourd', 'Gourds and squash', 'kg', 46::numeric),
  ('Ash Gourd', 'Gourds and squash', 'kg', 46::numeric),
  ('Pumpkin', 'Gourds and squash', 'kg', 46::numeric),
  ('Green Pumpkin', 'Gourds and squash', 'kg', 46::numeric),
  ('Yellow Pumpkin', 'Gourds and squash', 'kg', 46::numeric),
  ('Butternut Squash', 'Gourds and squash', 'kg', 46::numeric),
  ('Acorn Squash', 'Gourds and squash', 'kg', 46::numeric),
  ('Tinda', 'Gourds and squash', 'kg', 46::numeric),
  ('Pointed Gourd', 'Gourds and squash', 'kg', 46::numeric),
  ('Ivy Gourd', 'Gourds and squash', 'kg', 46::numeric),
  ('Chow Chow', 'Gourds and squash', 'kg', 46::numeric),
  ('Seem', 'Gourds and squash', 'kg', 46::numeric),
  ('French Beans', 'Beans and pods', '500g', 52::numeric),
  ('Broad Beans', 'Beans and pods', '500g', 52::numeric),
  ('Cluster Beans', 'Beans and pods', '500g', 52::numeric),
  ('Hyacinth Beans', 'Beans and pods', '500g', 52::numeric),
  ('Lima Beans', 'Beans and pods', '500g', 52::numeric),
  ('Runner Beans', 'Beans and pods', '500g', 52::numeric),
  ('Cowpeas', 'Beans and pods', '500g', 52::numeric),
  ('Edamame', 'Beans and pods', '500g', 52::numeric),
  ('Flat Beans', 'Beans and pods', '500g', 52::numeric),
  ('Green Beans', 'Beans and pods', '500g', 52::numeric),
  ('String Beans', 'Beans and pods', '500g', 52::numeric),
  ('Winged Bean', 'Beans and pods', '500g', 52::numeric),
  ('Velvet Bean', 'Beans and pods', '500g', 52::numeric),
  ('Guar Pods', 'Beans and pods', '500g', 52::numeric),
  ('Gawar', 'Beans and pods', '500g', 52::numeric),
  ('Sem Phali', 'Beans and pods', '500g', 52::numeric),
  ('Papdi', 'Beans and pods', '500g', 52::numeric),
  ('Val Papdi', 'Beans and pods', '500g', 52::numeric),
  ('Avarekai', 'Beans and pods', '500g', 52::numeric),
  ('Mochai', 'Beans and pods', '500g', 52::numeric),
  ('Snow Peas', 'Beans and pods', '500g', 75::numeric),
  ('Sugar Snap Peas', 'Beans and pods', '500g', 75::numeric),
  ('Fresh Peas', 'Beans and pods', '500g', 75::numeric),
  ('Fresh Chickpeas', 'Beans and pods', '500g', 75::numeric),
  ('Green Chickpeas', 'Beans and pods', '500g', 75::numeric),
  ('Fresh Pigeon Peas', 'Beans and pods', '500g', 75::numeric),
  ('Fresh Kidney Beans', 'Beans and pods', '500g', 75::numeric),
  ('Fresh Black Beans', 'Beans and pods', '500g', 75::numeric),
  ('Fresh Soybeans', 'Beans and pods', '500g', 75::numeric),
  ('Fresh Borlotti Beans', 'Beans and pods', '500g', 75::numeric),
  ('Fresh Lima Beans', 'Beans and pods', '500g', 75::numeric),
  ('Fresh Fava Beans', 'Beans and pods', '500g', 75::numeric),
  ('Fresh Peanuts', 'Beans and pods', '500g', 75::numeric),
  ('Horse Gram Pods', 'Beans and pods', '500g', 75::numeric),
  ('Green Peas', 'Peas and corn', '500g', 54::numeric),
  ('Corn', 'Peas and corn', '500g', 54::numeric),
  ('Baby Corn', 'Peas and corn', '500g', 54::numeric),
  ('Corn on Cob', 'Peas and corn', '500g', 54::numeric),
  ('Sweet Corn', 'Peas and corn', '500g', 54::numeric),
  ('Purple Corn', 'Peas and corn', '500g', 54::numeric),
  ('White Corn', 'Peas and corn', '500g', 54::numeric),
  ('Red Corn', 'Peas and corn', '500g', 54::numeric),
  ('Mushroom', 'Mushrooms', '200g', 72::numeric),
  ('Button Mushroom', 'Mushrooms', '200g', 72::numeric),
  ('Oyster Mushroom', 'Mushrooms', '200g', 72::numeric),
  ('Shiitake Mushroom', 'Mushrooms', '200g', 72::numeric),
  ('Enoki Mushroom', 'Mushrooms', '200g', 72::numeric),
  ('Portobello Mushroom', 'Mushrooms', '200g', 72::numeric),
  ('Broccoli', 'Cruciferous vegetables', 'kg', 55::numeric),
  ('Purple Broccoli', 'Cruciferous vegetables', 'kg', 55::numeric),
  ('Cauliflower', 'Cruciferous vegetables', 'kg', 55::numeric),
  ('Green Cauliflower', 'Cruciferous vegetables', 'kg', 55::numeric),
  ('Romanesco', 'Cruciferous vegetables', 'kg', 55::numeric),
  ('Baby Cauliflower', 'Cruciferous vegetables', 'kg', 55::numeric),
  ('Cabbage', 'Cruciferous vegetables', 'kg', 55::numeric),
  ('Red Cabbage', 'Cruciferous vegetables', 'kg', 55::numeric),
  ('Savoy Cabbage', 'Cruciferous vegetables', 'kg', 55::numeric),
  ('Napa Cabbage', 'Cruciferous vegetables', 'kg', 55::numeric),
  ('Purple Cabbage', 'Cruciferous vegetables', 'kg', 55::numeric),
  ('Bok Choy', 'Cruciferous vegetables', 'kg', 55::numeric),
  ('Baby Bok Choy', 'Cruciferous vegetables', 'kg', 55::numeric),
  ('Red Bok Choy', 'Cruciferous vegetables', 'kg', 55::numeric),
  ('Brussels Sprouts', 'Cruciferous vegetables', 'kg', 55::numeric),
  ('Chinese Broccoli', 'Cruciferous vegetables', 'kg', 55::numeric),
  ('Chinese Cabbage', 'Cruciferous vegetables', 'kg', 55::numeric),
  ('Spinach', 'Leafy vegetables', '250g', 24::numeric),
  ('Baby Spinach', 'Leafy vegetables', '250g', 24::numeric),
  ('Amaranth Leaves', 'Leafy vegetables', '250g', 24::numeric),
  ('Red Amaranth', 'Leafy vegetables', '250g', 24::numeric),
  ('Mustard Greens', 'Leafy vegetables', '250g', 24::numeric),
  ('Fenugreek Leaves', 'Leafy vegetables', '250g', 24::numeric),
  ('Coriander', 'Leafy vegetables', '250g', 24::numeric),
  ('Mint', 'Leafy vegetables', '250g', 24::numeric),
  ('Curry Leaves', 'Leafy vegetables', '250g', 24::numeric),
  ('Dill Leaves', 'Leafy vegetables', '250g', 24::numeric),
  ('Basil', 'Leafy vegetables', '250g', 24::numeric),
  ('Parsley', 'Leafy vegetables', '250g', 24::numeric),
  ('Celery', 'Leafy vegetables', '250g', 24::numeric),
  ('Rosemary', 'Leafy vegetables', '250g', 24::numeric),
  ('Thyme', 'Leafy vegetables', '250g', 24::numeric),
  ('Sage', 'Leafy vegetables', '250g', 24::numeric),
  ('Oregano', 'Leafy vegetables', '250g', 24::numeric),
  ('Lemongrass', 'Leafy vegetables', '250g', 24::numeric),
  ('Chives', 'Leafy vegetables', '250g', 24::numeric),
  ('Thai Basil', 'Leafy vegetables', '250g', 24::numeric),
  ('Kale', 'Leafy vegetables', '250g', 35::numeric),
  ('Green Kale', 'Leafy vegetables', '250g', 35::numeric),
  ('Red Kale', 'Leafy vegetables', '250g', 35::numeric),
  ('Baby Kale', 'Leafy vegetables', '250g', 35::numeric),
  ('Swiss Chard', 'Leafy vegetables', '250g', 35::numeric),
  ('Collard Greens', 'Leafy vegetables', '250g', 35::numeric),
  ('Beet Greens', 'Leafy vegetables', '250g', 35::numeric),
  ('Carrot Greens', 'Leafy vegetables', '250g', 35::numeric),
  ('Turnip Greens', 'Leafy vegetables', '250g', 35::numeric),
  ('Radish Greens', 'Leafy vegetables', '250g', 35::numeric),
  ('Mustard Leaves', 'Leafy vegetables', '250g', 35::numeric),
  ('Fenugreek Greens', 'Leafy vegetables', '250g', 35::numeric),
  ('Bathua Greens', 'Leafy vegetables', '250g', 35::numeric),
  ('Amaranth Greens', 'Leafy vegetables', '250g', 35::numeric),
  ('Malabar Spinach', 'Leafy vegetables', '250g', 35::numeric),
  ('Red Spinach', 'Leafy vegetables', '250g', 35::numeric),
  ('Poi Saag', 'Leafy vegetables', '250g', 35::numeric),
  ('Bathua', 'Leafy vegetables', '250g', 35::numeric),
  ('Chenopodium Greens', 'Leafy vegetables', '250g', 35::numeric),
  ('Chaulai', 'Leafy vegetables', '250g', 35::numeric),
  ('Sarson', 'Leafy vegetables', '250g', 35::numeric),
  ('Kulfa', 'Leafy vegetables', '250g', 35::numeric),
  ('Basella', 'Leafy vegetables', '250g', 35::numeric),
  ('Lettuce', 'Leafy vegetables', '250g', 45::numeric),
  ('Iceberg Lettuce', 'Leafy vegetables', '250g', 45::numeric),
  ('Romaine Lettuce', 'Leafy vegetables', '250g', 45::numeric),
  ('Butter Lettuce', 'Leafy vegetables', '250g', 45::numeric),
  ('Green Leaf Lettuce', 'Leafy vegetables', '250g', 45::numeric),
  ('Red Leaf Lettuce', 'Leafy vegetables', '250g', 45::numeric),
  ('Roman Lettuce', 'Leafy vegetables', '250g', 45::numeric),
  ('Frisee Lettuce', 'Leafy vegetables', '250g', 45::numeric),
  ('Radicchio', 'Leafy vegetables', '250g', 45::numeric),
  ('Chicory', 'Leafy vegetables', '250g', 45::numeric),
  ('Endive', 'Leafy vegetables', '250g', 45::numeric),
  ('Arugula', 'Leafy vegetables', '250g', 45::numeric),
  ('Watercress', 'Leafy vegetables', '250g', 45::numeric),
  ('Mizuna', 'Leafy vegetables', '250g', 45::numeric),
  ('Tatsoi', 'Leafy vegetables', '250g', 45::numeric),
  ('Komatsuna', 'Leafy vegetables', '250g', 45::numeric),
  ('Broccoli Rabe', 'Leafy vegetables', '250g', 45::numeric),
  ('Rapini', 'Leafy vegetables', '250g', 45::numeric),
  ('Sorrel', 'Leafy vegetables', '250g', 45::numeric),
  ('Sorrel Leaves', 'Leafy vegetables', '250g', 45::numeric),
  ('Water Spinach', 'Leafy vegetables', '250g', 45::numeric),
  ('Morning Glory', 'Leafy vegetables', '250g', 45::numeric),
  ('Napa Spinach', 'Leafy vegetables', '250g', 45::numeric),
  ('Curry Leaf Sprigs', 'Leafy vegetables', '100g', 30::numeric),
  ('Moringa Leaves', 'Leafy vegetables', '100g', 30::numeric),
  ('Gongura Leaves', 'Leafy vegetables', '100g', 30::numeric),
  ('Colocasia Leaves', 'Leafy vegetables', '100g', 30::numeric),
  ('Betel Leaves', 'Leafy vegetables', '100g', 30::numeric),
  ('Drumstick Leaves', 'Leafy vegetables', '100g', 30::numeric),
  ('Tamarind Leaves', 'Leafy vegetables', '100g', 30::numeric),
  ('Roselle Leaves', 'Leafy vegetables', '100g', 30::numeric),
  ('Purslane', 'Leafy vegetables', '100g', 30::numeric),
  ('Agathi Leaves', 'Leafy vegetables', '100g', 30::numeric),
  ('Pumpkin Leaves', 'Leafy vegetables', '100g', 30::numeric),
  ('Sweet Potato Leaves', 'Leafy vegetables', '100g', 30::numeric),
  ('Taro Leaves', 'Leafy vegetables', '100g', 30::numeric),
  ('Asparagus', 'Specialty vegetables', '500g', 120::numeric),
  ('Artichoke', 'Specialty vegetables', '500g', 120::numeric),
  ('Bamboo Shoots', 'Specialty vegetables', '500g', 120::numeric),
  ('Bean Sprouts', 'Specialty vegetables', '500g', 120::numeric),
  ('Alfalfa Sprouts', 'Specialty vegetables', '500g', 120::numeric),
  ('Methi Sprouts', 'Specialty vegetables', '500g', 120::numeric),
  ('Radish Sprouts', 'Specialty vegetables', '500g', 120::numeric),
  ('Mustard Sprouts', 'Specialty vegetables', '500g', 120::numeric),
  ('Lotus Root', 'Specialty vegetables', 'kg', 65::numeric),
  ('Lotus Stem', 'Specialty vegetables', 'kg', 65::numeric),
  ('Water Chestnut', 'Specialty vegetables', 'kg', 65::numeric),
  ('Raw Papaya', 'Specialty vegetables', 'kg', 65::numeric),
  ('Raw Banana', 'Specialty vegetables', 'kg', 65::numeric),
  ('Raw Jackfruit', 'Specialty vegetables', 'kg', 65::numeric),
  ('Drumstick', 'Specialty vegetables', 'kg', 65::numeric),
  ('Moringa Pods', 'Specialty vegetables', 'kg', 65::numeric),
  ('Banana Flower', 'Specialty vegetables', 'kg', 65::numeric),
  ('Banana Stem', 'Specialty vegetables', 'kg', 65::numeric),
  ('Pumpkin Flower', 'Specialty vegetables', 'kg', 65::numeric),
  ('Zucchini Flower', 'Specialty vegetables', 'kg', 65::numeric),
  ('Bottle Gourd Flower', 'Specialty vegetables', 'kg', 65::numeric),
  ('Ridge Gourd Flower', 'Specialty vegetables', 'kg', 65::numeric),
  ('Kachri', 'Indian regional vegetables', 'kg', 55::numeric),
  ('Kakora', 'Indian regional vegetables', 'kg', 55::numeric),
  ('Kantola', 'Indian regional vegetables', 'kg', 55::numeric),
  ('Teasel Gourd', 'Indian regional vegetables', 'kg', 55::numeric),
  ('Karela Baby', 'Indian regional vegetables', 'kg', 55::numeric),
  ('Parwal', 'Indian regional vegetables', 'kg', 55::numeric),
  ('Kundru', 'Indian regional vegetables', 'kg', 55::numeric),
  ('Taro', 'Indian regional vegetables', 'kg', 70::numeric),
  ('Apple', 'Apples', 'kg', 168::numeric),
  ('Red Apple', 'Apples', 'kg', 168::numeric),
  ('Green Apple', 'Apples', 'kg', 168::numeric),
  ('Royal Gala Apple', 'Apples', 'kg', 168::numeric),
  ('Fuji Apple', 'Apples', 'kg', 168::numeric),
  ('Granny Smith Apple', 'Apples', 'kg', 168::numeric),
  ('Pink Lady Apple', 'Apples', 'kg', 168::numeric),
  ('Washington Apple', 'Apples', 'kg', 168::numeric),
  ('Ambri Apple', 'Apples', 'kg', 168::numeric),
  ('Kinnaur Apple', 'Apples', 'kg', 168::numeric),
  ('Banana', 'Bananas', 'dozen', 62::numeric),
  ('Robusta Banana', 'Bananas', 'dozen', 62::numeric),
  ('Cavendish Banana', 'Bananas', 'dozen', 62::numeric),
  ('Yelakki Banana', 'Bananas', 'dozen', 62::numeric),
  ('Nendran Banana', 'Bananas', 'dozen', 62::numeric),
  ('Red Banana', 'Bananas', 'dozen', 62::numeric),
  ('Plantain', 'Bananas', 'dozen', 62::numeric),
  ('Rasthali Banana', 'Bananas', 'dozen', 62::numeric),
  ('Poovan Banana', 'Bananas', 'dozen', 62::numeric),
  ('Mango', 'Mangoes', 'kg', 142::numeric),
  ('Alphonso Mango', 'Mangoes', 'kg', 142::numeric),
  ('Kesar Mango', 'Mangoes', 'kg', 142::numeric),
  ('Dasheri Mango', 'Mangoes', 'kg', 142::numeric),
  ('Langra Mango', 'Mangoes', 'kg', 142::numeric),
  ('Chausa Mango', 'Mangoes', 'kg', 142::numeric),
  ('Totapuri Mango', 'Mangoes', 'kg', 142::numeric),
  ('Banganapalli Mango', 'Mangoes', 'kg', 142::numeric),
  ('Himsagar Mango', 'Mangoes', 'kg', 142::numeric),
  ('Safeda Mango', 'Mangoes', 'kg', 142::numeric),
  ('Malgova Mango', 'Mangoes', 'kg', 142::numeric),
  ('Sindhura Mango', 'Mangoes', 'kg', 142::numeric),
  ('Amrapali Mango', 'Mangoes', 'kg', 142::numeric),
  ('Neelam Mango', 'Mangoes', 'kg', 142::numeric),
  ('Raspuri Mango', 'Mangoes', 'kg', 142::numeric),
  ('Orange', 'Citrus fruit', 'kg', 92::numeric),
  ('Valencia Orange', 'Citrus fruit', 'kg', 92::numeric),
  ('Nagpur Orange', 'Citrus fruit', 'kg', 92::numeric),
  ('Kinnow', 'Citrus fruit', 'kg', 92::numeric),
  ('Mandarin', 'Citrus fruit', 'kg', 92::numeric),
  ('Tangerine', 'Citrus fruit', 'kg', 92::numeric),
  ('Blood Orange', 'Citrus fruit', 'kg', 92::numeric),
  ('Sweet Lime', 'Citrus fruit', 'kg', 92::numeric),
  ('Lemon', 'Citrus fruit', 'kg', 92::numeric),
  ('Meyer Lemon', 'Citrus fruit', 'kg', 92::numeric),
  ('Lime', 'Citrus fruit', 'kg', 92::numeric),
  ('Mosambi', 'Citrus fruit', 'kg', 92::numeric),
  ('Grapefruit', 'Citrus fruit', 'kg', 92::numeric),
  ('Pomelo', 'Citrus fruit', 'kg', 92::numeric),
  ('Persian Lime', 'Citrus fruit', 'kg', 92::numeric),
  ('Guava', 'Tropical fruits', 'kg', 85::numeric),
  ('Pink Guava', 'Tropical fruits', 'kg', 85::numeric),
  ('White Guava', 'Tropical fruits', 'kg', 85::numeric),
  ('Pear', 'Tropical fruits', 'kg', 85::numeric),
  ('Asian Pear', 'Tropical fruits', 'kg', 85::numeric),
  ('Bartlett Pear', 'Tropical fruits', 'kg', 85::numeric),
  ('Green Pear', 'Tropical fruits', 'kg', 85::numeric),
  ('Red Pear', 'Tropical fruits', 'kg', 85::numeric),
  ('Papaya', 'Tropical fruits', 'piece', 78::numeric),
  ('Red Lady Papaya', 'Tropical fruits', 'piece', 78::numeric),
  ('Pineapple', 'Tropical fruits', 'piece', 78::numeric),
  ('Baby Pineapple', 'Tropical fruits', 'piece', 78::numeric),
  ('Dragon Fruit', 'Tropical fruits', 'piece', 78::numeric),
  ('Red Dragon Fruit', 'Tropical fruits', 'piece', 78::numeric),
  ('White Dragon Fruit', 'Tropical fruits', 'piece', 78::numeric),
  ('Dragon Fruit Yellow', 'Tropical fruits', 'piece', 78::numeric),
  ('Avocado', 'Tropical fruits', 'piece', 78::numeric),
  ('Hass Avocado', 'Tropical fruits', 'piece', 78::numeric),
  ('Fuerte Avocado', 'Tropical fruits', 'piece', 78::numeric),
  ('Kiwi', 'Tropical fruits', 'piece', 78::numeric),
  ('Golden Kiwi', 'Tropical fruits', 'piece', 78::numeric),
  ('Green Kiwi', 'Tropical fruits', 'piece', 78::numeric),
  ('Kiwi Berry', 'Tropical fruits', 'piece', 78::numeric),
  ('Coconut', 'Tropical fruits', 'piece', 65::numeric),
  ('Tender Coconut', 'Tropical fruits', 'piece', 65::numeric),
  ('Chikoo', 'Tropical fruits', 'piece', 65::numeric),
  ('Sapota', 'Tropical fruits', 'piece', 65::numeric),
  ('Custard Apple', 'Tropical fruits', 'piece', 65::numeric),
  ('Sitaphal', 'Tropical fruits', 'piece', 65::numeric),
  ('Ramphal', 'Tropical fruits', 'piece', 65::numeric),
  ('Soursop', 'Tropical fruits', 'piece', 65::numeric),
  ('Cherimoya', 'Tropical fruits', 'piece', 65::numeric),
  ('Jackfruit', 'Tropical fruits', 'piece', 65::numeric),
  ('Raw Jackfruit', 'Tropical fruits', 'piece', 65::numeric),
  ('Breadfruit', 'Tropical fruits', 'piece', 65::numeric),
  ('Lychee', 'Tropical fruits', 'piece', 65::numeric),
  ('Rambutan', 'Tropical fruits', 'piece', 65::numeric),
  ('Longan', 'Tropical fruits', 'piece', 65::numeric),
  ('Mangosteen', 'Tropical fruits', 'piece', 65::numeric),
  ('Mangosteen Purple', 'Tropical fruits', 'piece', 65::numeric),
  ('Durian', 'Tropical fruits', 'piece', 65::numeric),
  ('Passion Fruit', 'Tropical fruits', 'piece', 65::numeric),
  ('Star Fruit', 'Tropical fruits', 'piece', 65::numeric),
  ('Carambola', 'Tropical fruits', 'piece', 65::numeric),
  ('Watermelon', 'Melons and grapes', 'kg', 86::numeric),
  ('Yellow Watermelon', 'Melons and grapes', 'kg', 86::numeric),
  ('Muskmelon', 'Melons and grapes', 'kg', 86::numeric),
  ('Cantaloupe', 'Melons and grapes', 'kg', 86::numeric),
  ('Honeydew Melon', 'Melons and grapes', 'kg', 86::numeric),
  ('Grapes', 'Melons and grapes', 'kg', 86::numeric),
  ('Green Grapes', 'Melons and grapes', 'kg', 86::numeric),
  ('Red Grapes', 'Melons and grapes', 'kg', 86::numeric),
  ('Black Grapes', 'Melons and grapes', 'kg', 86::numeric),
  ('Thompson Seedless Grapes', 'Melons and grapes', 'kg', 86::numeric),
  ('Flame Seedless Grapes', 'Melons and grapes', 'kg', 86::numeric),
  ('Concord Grapes', 'Melons and grapes', 'kg', 86::numeric),
  ('Strawberry', 'Berries', '250g', 178::numeric),
  ('Blueberry', 'Berries', '250g', 178::numeric),
  ('Raspberry', 'Berries', '250g', 178::numeric),
  ('Blackberry', 'Berries', '250g', 178::numeric),
  ('Cranberry', 'Berries', '250g', 178::numeric),
  ('Mulberry', 'Berries', '250g', 178::numeric),
  ('White Mulberry', 'Berries', '250g', 178::numeric),
  ('Black Mulberry', 'Berries', '250g', 178::numeric),
  ('Red Mulberry', 'Berries', '250g', 178::numeric),
  ('Gooseberry', 'Berries', '250g', 178::numeric),
  ('Indian Gooseberry', 'Berries', '250g', 178::numeric),
  ('Amla', 'Berries', '250g', 178::numeric),
  ('Cape Gooseberry', 'Berries', '250g', 178::numeric),
  ('Golden Berry', 'Berries', '250g', 178::numeric),
  ('Blackcurrant', 'Berries', '250g', 178::numeric),
  ('Redcurrant', 'Berries', '250g', 178::numeric),
  ('Whitecurrant', 'Berries', '250g', 178::numeric),
  ('Elderberry', 'Berries', '250g', 178::numeric),
  ('Boysenberry', 'Berries', '250g', 178::numeric),
  ('Loganberry', 'Berries', '250g', 178::numeric),
  ('Gooseberry Green', 'Berries', '250g', 178::numeric),
  ('Gooseberry Red', 'Berries', '250g', 178::numeric),
  ('Peach', 'Stone fruits', '500g', 118::numeric),
  ('White Peach', 'Stone fruits', '500g', 118::numeric),
  ('Nectarine', 'Stone fruits', '500g', 118::numeric),
  ('Plum', 'Stone fruits', '500g', 118::numeric),
  ('Black Plum', 'Stone fruits', '500g', 118::numeric),
  ('Red Plum', 'Stone fruits', '500g', 118::numeric),
  ('Apricot', 'Stone fruits', '500g', 118::numeric),
  ('Cherry', 'Stone fruits', '500g', 118::numeric),
  ('Sweet Cherry', 'Stone fruits', '500g', 118::numeric),
  ('Sour Cherry', 'Stone fruits', '500g', 118::numeric),
  ('Fig', 'Stone fruits', '500g', 95::numeric),
  ('Fresh Fig', 'Stone fruits', '500g', 95::numeric),
  ('Fig Green', 'Stone fruits', '500g', 95::numeric),
  ('Fig Black', 'Stone fruits', '500g', 95::numeric),
  ('Date', 'Stone fruits', '500g', 95::numeric),
  ('Fresh Dates', 'Stone fruits', '500g', 95::numeric),
  ('Persimmon', 'Stone fruits', '500g', 95::numeric),
  ('Persimmon Fuyu', 'Stone fruits', '500g', 95::numeric),
  ('Persimmon Hachiya', 'Stone fruits', '500g', 95::numeric),
  ('Pomegranate', 'Exotic fruits', 'kg', 120::numeric),
  ('Red Pomegranate', 'Exotic fruits', 'kg', 120::numeric),
  ('Quince', 'Exotic fruits', 'kg', 120::numeric),
  ('Loquat', 'Exotic fruits', 'kg', 120::numeric),
  ('Medlar', 'Exotic fruits', 'kg', 120::numeric),
  ('Miracle Fruit', 'Exotic fruits', 'kg', 120::numeric),
  ('Feijoa', 'Exotic fruits', 'kg', 120::numeric),
  ('Kiwano', 'Exotic fruits', 'kg', 120::numeric),
  ('Horned Melon', 'Exotic fruits', 'kg', 120::numeric),
  ('Tamarillo', 'Exotic fruits', 'kg', 120::numeric),
  ('White Sapote', 'Exotic fruits', 'kg', 120::numeric),
  ('Black Sapote', 'Exotic fruits', 'kg', 120::numeric),
  ('Mamey Sapote', 'Exotic fruits', 'kg', 120::numeric),
  ('Canistel', 'Exotic fruits', 'kg', 120::numeric),
  ('Lucuma', 'Exotic fruits', 'kg', 120::numeric),
  ('Ackee', 'Exotic fruits', 'kg', 120::numeric),
  ('Jabuticaba', 'Exotic fruits', 'kg', 120::numeric),
  ('Langsat', 'Exotic fruits', 'kg', 120::numeric),
  ('Pulasan', 'Exotic fruits', 'kg', 120::numeric),
  ('Santol', 'Exotic fruits', 'kg', 120::numeric),
  ('Salak Fruit', 'Exotic fruits', 'kg', 120::numeric),
  ('Kei Apple', 'Exotic fruits', 'kg', 120::numeric),
  ('Noni Fruit', 'Exotic fruits', 'kg', 120::numeric),
  ('Bilimbi', 'Exotic fruits', 'kg', 120::numeric),
  ('Ambarella', 'Exotic fruits', 'kg', 120::numeric),
  ('Hog Plum', 'Exotic fruits', 'kg', 120::numeric),
  ('June Plum', 'Exotic fruits', 'kg', 120::numeric),
  ('Cempedak', 'Exotic fruits', 'kg', 120::numeric),
  ('Marang', 'Exotic fruits', 'kg', 120::numeric),
  ('Breadnut', 'Exotic fruits', 'kg', 120::numeric),
  ('Mammee Apple', 'Exotic fruits', 'kg', 120::numeric),
  ('Malay Apple', 'Exotic fruits', 'kg', 120::numeric),
  ('Bignay', 'Exotic fruits', 'kg', 120::numeric),
  ('Jamun', 'Exotic fruits', 'kg', 90::numeric),
  ('Karonda', 'Exotic fruits', 'kg', 90::numeric),
  ('Ber', 'Exotic fruits', 'kg', 90::numeric),
  ('Indian Jujube', 'Exotic fruits', 'kg', 90::numeric),
  ('Bael', 'Exotic fruits', 'kg', 90::numeric),
  ('Wood Apple', 'Exotic fruits', 'kg', 90::numeric),
  ('Kokum', 'Exotic fruits', 'kg', 90::numeric),
  ('Phalsa', 'Exotic fruits', 'kg', 90::numeric),
  ('Tamarind', 'Exotic fruits', 'kg', 90::numeric),
  ('Raw Tamarind', 'Exotic fruits', 'kg', 90::numeric),
  ('Elephant Apple', 'Exotic fruits', 'kg', 90::numeric),
  ('Star Gooseberry', 'Exotic fruits', 'kg', 90::numeric),
  ('Barbados Cherry', 'Exotic fruits', 'kg', 90::numeric),
  ('Acerola', 'Exotic fruits', 'kg', 90::numeric),
  ('Water Apple', 'Exotic fruits', 'kg', 90::numeric),
  ('Wax Apple', 'Exotic fruits', 'kg', 90::numeric),
  ('Java Apple', 'Exotic fruits', 'kg', 90::numeric),
  ('Rose Apple', 'Exotic fruits', 'kg', 90::numeric),
  ('Snake Fruit', 'Exotic fruits', 'kg', 90::numeric),
  ('Salak', 'Exotic fruits', 'kg', 90::numeric)
), priced AS (
  SELECT name, category, unit,
    round(base_price * (1 + (((abs(hashtext(name)) % 5) - 2) * 0.025)), 2) AS base,
    abs(hashtext(name)) AS product_hash
  FROM seed_data
)
INSERT INTO public.products (name, category, unit, source_prices)
SELECT name, category, unit,
  jsonb_build_array(
    jsonb_build_object('source', 'BigBasket', 'price', round(base * (CASE WHEN product_hash % 17 = 0 THEN 0.86 ELSE 1 + (((product_hash % 5) - 2) * 0.018) END), 2)),
    jsonb_build_object('source', 'Blinkit', 'price', round(base * (CASE WHEN product_hash % 19 = 0 THEN 0.90 ELSE 1 + ((abs(hashtext(name || 'coupon')) % 7 - 3) * 0.015) END), 2)),
    jsonb_build_object('source', 'Zepto', 'price', round(base * (CASE WHEN product_hash % 23 = 0 THEN 0.83 ELSE 1 + ((abs(hashtext(name || 'cashback')) % 5 - 2) * 0.02) END), 2)),
    jsonb_build_object('source', 'Swiggy Instamart', 'price', round(base * (CASE WHEN product_hash % 29 = 0 THEN 1.10 ELSE 1 + ((abs(hashtext(name || 'card')) % 7 - 3) * 0.018) END), 2))
  )
FROM priced
ON CONFLICT (name, unit) DO UPDATE SET
  category = EXCLUDED.category,
  source_prices = EXCLUDED.source_prices;
